# baseURL = 'https://blog.u-map.cn'
baseURL = 'https://blog.u-map.cn'
languageCode = 'zh-cn'
title = 'ä¸åœ¨åŒ—æçš„åŒ—æç†ŠğŸ»â€â„ï¸'
theme = 'github-style'
enableEmoji = true

[params]
author = "Luoooo"
location = "China"
userStatusEmoji = "ğŸ»â€â„ï¸"
description = 'åŒ—æç†Šä¸ºä»€ä¹ˆä¸åœ¨åŒ—æ'

# avatar = 'https://avatars.githubusercontent.com/u/29565303?v=4'
avatar = 'https://gravatar.kuibu.net/avatar/50851777fd7f7e6e7a3cc62406923c14?s=400'
# avatar = 'https://cdn.v2ex.com/gravatar/50851777fd7f7e6e7a3cc62406923c14'
# avatar = 'https://gravatar.loli.net/avatar/50851777fd7f7e6e7a3cc62406923c14?s=400&r=G'
favicon = "https://gravatar.loli.net/avatar/50851777fd7f7e6e7a3cc62406923c14"

github = "luo-geng"
email = 'rogan.luo@qq.com'
url = "https://blog.u-map.cn"

keywords = "blog"
rss = true

# lastmod = true

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
