# baseURL = 'https://blog.u-map.cn'
baseURL = '/'
languageCode = 'zh-cn'
title = 'ä¸åœ¨åŒ—æçš„åŒ—æç†ŠğŸ»â€â„ï¸'
theme = 'github-style'

[params]
author = "Luoooo"
location = "China"
userStatusEmoji = "ğŸ»â€â„ï¸"
description = 'åŒ—æç†Šä¸ºä»€ä¹ˆä¸åœ¨åŒ—æ'

avatar = 'https://avatars.githubusercontent.com/u/29565303?v=4'
favicon = "https://avatars.githubusercontent.com/u/29565303?v=4"

github = "luo-geng"
email = 'rogan.luo@qq.com'
url = "https://blog.u-map.cn"

keywords = "blog"
rss = true


[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]
